name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  TZ: "Asia/Tokyo"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v4
      - run: npm ci
      - name: Run tests
        run: npm test
